### ISSUE TITLE
Error in ciftify_peaktable and ciftify_statclust_report

### ISSUE THREAD

**Issue by kmanoli** [edickie/ciftify#170]
Hello,

I'm trying to get more information about a seed-to-voxel correlation dscalar file, generated with ciftify_seed_corr. I tried ciftify_peaktable and ciftify_statclust_report but got the same error: AttributeError: 'Index' object has no attribute 'get_values'. I used these functions with and without extra options, but the errors persist. I should mention that ciftify_statclust_report does generate a _clust.dlabel.nii, but no csv file. Any help will be greatly appreciated! 

```
Traceback (most recent call last):
  File "/Users/katerina/opt/anaconda3/bin/ciftify_peaktable", line 8, in <module>
    sys.exit(main())
  File "/Users/katerina/opt/anaconda3/lib/python3.9/site-packages/ciftify/bin/ciftify_statclust_report.py", line 426, in main
    ret = run_ciftify_dlabel_report(arguments, tmpdir)
  File "/Users/katerina/opt/anaconda3/lib/python3.9/site-packages/ciftify/bin/ciftify_statclust_report.py", line 182, in run_ciftify_dlabel_report
    for pd_idx in df.index.get_values():
AttributeError: 'Index' object has no attribute 'get_values'
```

Pandas version: 1.3.4
Python version: 3.9.7

Best,
Katerina

**Comment by joebathelt** [comment]
Hi Katerina,
I had the same issue. I think the reason is that the `df.index.get_values()` syntax is no longer supported in pandas (see [pandas documentation](https://pandas.pydata.org/pandas-docs/version/0.25/reference/api/pandas.Index.get_values.html)). As a workaround, I created a conda environment with an older version of pandas: 

```bash
conda create -n 'ciftify'  
conda activate ciftify  
conda install python=3.7  
conda install pandas=0.24 
pip install -U ciftify
```
