### ISSUE TITLE
permission error 

### ISSUE THREAD

**Issue by andraderenew** [edickie/ciftify#179]
Dear community:
I have the following error. I tried running from sudo su but the same error pops up. 

ciftify_recon_all --surf-reg FS --fs-subjects-dir '/media/andraderenew/Elements/backup_1TB/image_databases/anorexia/results/Freesurfer/controls'  --ciftify-work-dir '/media/andraderenew/Elements/backup_1TB/image_databases/anorexia/results/Diffusion/ciftify'   s25633_T1MPRAGE_1mm_reconall
Traceback (most recent call last):
  File "/home/andraderenew/anaconda3/bin/ciftify_recon_all", line 8, in <module>
    sys.exit(main())
  File "/home/andraderenew/anaconda3/lib/python3.9/site-packages/ciftify/bin/ciftify_recon_all.py", line 1567, in main
    run_ciftify_recon_all(tmpdir, settings)
  File "/home/andraderenew/anaconda3/lib/python3.9/site-packages/ciftify/bin/ciftify_recon_all.py", line 123, in run_ciftify_recon_all
    run_default_workflow(temp_dir, settings, meshes, expected_labels, fs_version)
  File "/home/andraderenew/anaconda3/lib/python3.9/site-packages/ciftify/bin/ciftify_recon_all.py", line 155, in run_default_workflow
    create_cifti_subcortical_ROIs(subject.atlas_space_dir, settings, temp_dir)
  File "/home/andraderenew/anaconda3/lib/python3.9/site-packages/ciftify/bin/ciftify_recon_all.py", line 762, in create_cifti_subcortical_ROIs
    link_to_template_file(settings, atlas_ROIs,
  File "/home/andraderenew/anaconda3/lib/python3.9/site-packages/ciftify/bin/ciftify_recon_all.py", line 532, in link_to_template_file
    os.symlink(os.path.relpath(via_path, os.path.dirname(subject_file)),
PermissionError: [Errno 1] Operation not permitted: '../../../zz_templates/Atlas_ROIs.2.nii.gz' -> '/media/andraderenew/Elements/backup_1TB/image_databases/anorexia/results/Diffusion/ciftify/s25633_T1MPRAGE_1mm_reconall/MNINonLinear/ROIs/Atlas_ROIs.2.nii.gz'

**Comment by edickie** [comment]
It looks like your filesystem might not work well with symlinks. Try
running everything with the ` --no-symlinks` flag.

**Comment by andraderenew** [comment]
sorry to ask here may be it's best if I open another thread. My question is how to use more than one cpu cores? Is there any flag to accelarate the processing? I have 8 cores and a GPU. I have seen in the docuementation it is related to parallel but I find it diffuclt to follow from the example. If there's no other way I'll have to do it.

**Comment by andraderenew** [comment]
I have another error. 

ciftify_recon_all --surf-reg FS --fs-subjects-dir '/media/andraderenew/Elements/backup_1TB/image_databases/anorexia/results/Freesurfer/controls'  --ciftify-work-dir '/media/andraderenew/Elements/backup_1TB/image_databases/anorexia/results/Diffusion/ciftify'   s25634_T1MPRAGE_1mm_reconall --no-symlinks --n_cpus 8
cmd: mris_convert /media/andraderenew/Elements/backup_1TB/image_databases/anorexia/results/Freesurfer/controls/s25634_T1MPRAGE_1mm_reconall/surf/lh.pial /media/andraderenew/Elements/backup_1TB/image_databases/anorexia/results/Diffusion/ciftify/s25634_T1MPRAGE_1mm_reconall/T1w/Native/s25634_T1MPRAGE_1mm_reconall.L.pial.native.surf.gii 
 Failed with returncode 255
error: No such file or directory
error: MRISread(/media/andraderenew/Elements/backup_1TB/image_databases/anorexia/results/Freesurfer/controls/s25634_T1MPRAGE_1mm_reconall/surf/lh.pial): could not open file
error: No such file or directory
error: mris_convert: could not read surface file /media/andraderenew/Elements/backup_1TB/image_databases/anorexia/results/Freesurfer/controls/s25634_T1MPRAGE_1mm_reconall/surf/lh.pial

**Comment by edickie** [comment]
how are your Freesurfer outputs organized - does the file
/media/andraderenew/Elements/backup_1TB/image_databases/anorexia/results/Freesurfer/controls/s25634_T1MPRAGE_1mm_reconall/surf/lh.pial
exist?

**Comment by andraderenew** [comment]
I was surprised to verify I do have lh.pial.T1 but not lh.pial. So that must be the issue. Shall I restart recon-all? Is it a failed reconall? May be I would end up without lh.pial again I have no idea. May be the flag autorecon-pial would work.

**Comment by andraderenew** [comment]
I have read in freesurfer mail archive that perhaps lh.pial and lh.pialT1 are the same file? Any comments on this?

**Comment by andraderenew** [comment]
which version of Freesurfer am I supposed to be using? may be 7.3.2 isn't creating lh.pial but symbolic link from lh.pial to  lh.pial.T1 as I am reading from freesurfer mail archive. But I'm not sure.
